services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    hostname: caddy
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/etc/caddy/certs
      - caddy_data:/data
      - caddy_config:/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  caddy_data:
  caddy_config:
